### ISSUE TITLE
Show oas3 API docs instead of deprecated swagger versions

### ISSUE THREAD

**Issue by seanhinde** [aeternity/api-docs#11]
After discussion:
[Sean Hinde]
Dimitar mentioned that we have some wish to move people towards the /v3 HTTP API. Wondering what we need to do to get the  v3 docs available at https://api-docs.aeternity.io/ (edited) 

[dincho]
a change to this function: https://github.com/aeternity/api-docs/blob/master/main.js#L2

function swaggerUrl(version) {

what the new swagger path ?

[Dimitar Ivanov]
s/swagger/oas3

**Comment by dincho** [comment]
done in https://github.com/aeternity/api-docs/pull/12
